export const USER_REPOSITORY = 'USER_REPOSITORY';
export const BUSINESS_REPOSITORY = 'BUSINESS_REPOSITORY';
export const COURT_REPOSITORY = 'COURT_REPOSITORY';
export const BOOKING_REPOSITORY = 'BOOKING_REPOSITORY';
export const AVAILABILITY_RULE_REPOSITORY = 'AVAILABILITY_RULE_REPOSITORY';
export const COURT_AVAILABILITY_REPOSITORY = 'COURT_AVAILABILITY_REPOSITORY';
export const EXCEPTION_RULE_REPOSITORY = 'EXCEPTION_RULE_REPOSITORY';
export const COURT_EXCEPTION_REPOSITORY = 'COURT_EXCEPTION_REPOSITORY';
export const BUSINESS_USER_REPOSITORY = 'BUSINESS_USER_REPOSITORY';
export const PLAN_REPOSITORY = 'PLAN_REPOSITORY';
export const SUBSCRIPTION_REPOSITORY = 'SUBSCRIPTION_REPOSITORY';
export const BUSINESS_FEATURE_REPOSITORY = 'BUSINESS_FEATURE_REPOSITORY';
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const PASSWORD_RESET_TOKEN_REPOSITORY =
  'PASSWORD_RESET_TOKEN_REPOSITORY';
export const BUSINESS_INVITATION_REPOSITORY = 'BUSINESS_INVITATION_REPOSITORY';
