export const USER_REPOSITORY = 'USER_REPOSITORY';
export const BUSINESS_REPOSITORY = 'BUSINESS_REPOSITORY';
export const COURT_REPOSITORY = 'COURT_REPOSITORY';
export const BOOKING_REPOSITORY = 'BOOKING_REPOSITORY';
export const AVAILABILITY_RULE_REPOSITORY = 'AVAILABILITY_RULE_REPOSITORY';
export const COURT_AVAILABILITY_REPOSITORY = 'COURT_AVAILABILITY_REPOSITORY';
export const EXCEPTION_RULE_REPOSITORY = 'EXCEPTION_RULE_REPOSITORY';
export const COURT_EXCEPTION_REPOSITORY = 'COURT_EXCEPTION_REPOSITORY';
